weights : imagenet
img_height : 299
img_width : 299
augmenting_factor : 1.5
class_num: 2
batch_size: 16
batch_size_u: 5
save_model: False
x_col_name : imagen
y_col_name : clase
ruta_base : data/
transfer_learning : classic
save_figs : 
modalidad: 
    ultra-fast: 
        train_epocs: 1
        batch_epocs: 1
save_path_logs : logs/
id : 33
path_label_stats : results/data_label_stats_
ssl_threshold : 0.90
dataset_base : NWPU-RESISC45
split_train_test : 5
split_kfold : 4