id : 33
dataset: satellital
dataset_base : NWPU-RESISC45
weights : imagenet
img_height : 299
img_width : 299
aug_factor : 1.5
class_num: 45
batch_size: 16
batch_size_u: 5
save_model: False
x_col_name : image
y_col_name : class
ruta_base : data/
transfer_learning : classic
save_fig_path : plots/
modality: ultra-fast
save_path_logs : logs/
path_label_stats : stats/data_label_stats_
ssl_threshold : 0.90
split_train_test : 5
split_kfold : 4