id : 77
dataset: satellital
dataset_base: NWPU-RESISC45
weights: imagenet
train_epochs: 30
learning_rate: 1e-5
aug_factor: 2
ssl_threshold: 0.90
split_train_test: 5
split_kfold: 4
num_kfold: 4
early_stopping: True
reduce_lr: False
aug_stages: False
class_weight: False
use_stage_config: False
cm_normalize: True
checkpoint: False
restart_weights: True
batch_size_u: 5
batch_size: 32
img_height: 256
img_width: 256
transfer_learning: classic
x_col_name: image
y_col_name: class
metrics: weighted
ruta_base: /home/miguel/msc-tesis/ssl_satellital/data
save_path_fig: plots/
save_path_logs: logs/
save_path_results: results/
save_path_stats: stats/
save_path_models: models/
save_path_data: data/